bot:
  api_key: ''
  name: OpenAI
flask:
  debug: true
  host: localhost
  port: 5000
runtime:
  agent_path: storage/agent
  current_session_id: 1f7706cd-170f-4807-ad27-727500c720e5
  history_path: storage/history
